# Generated by Django 4.1.7 on 2023-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
    ]
