# Generated by Django 4.1.7 on 2023-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_imdb_id_movie_imdbid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
