# Generated by Django 4.1.7 on 2023-03-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('likely_to_watch', models.CharField(blank=True, choices=[('Never', 'I never want to watch it'), ('Not interested', 'Not interested'), ('Maybe', 'Maybe'), ('Interested', 'Interested'), ('ASAP', 'I want to watch it ASAP')], max_length=20, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('comparison_count', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.participant')),
            ],
            options={
                'unique_together': {('participant', 'movie')},
            },
        ),
    ]
