# Generated by Django 4.1.7 on 2023-04-04 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_interaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='has_seen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
