# Generated by Django 4.1.7 on 2023-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_interaction_has_seen_alter_interaction_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='map',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
