# Generated by Django 4.1.7 on 2023-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_interaction_seen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='judge_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='pref_judge_finished',
            field=models.BooleanField(default=False),
        ),
    ]
