# Generated by Django 4.1.7 on 2023-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_interaction_likely_to_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='judge_finished',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pref_judge_finished',
        ),
        migrations.AddField(
            model_name='participant',
            name='remaining_judge_actions',
            field=models.IntegerField(default=0),
        ),
    ]
