# Generated by Django 4.2.2 on 2023-06-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_participant_taken_initial_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
