# Generated by Django 4.1.7 on 2023-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('imbd_id', models.CharField(max_length=40)),
                ('year', models.IntegerField(default=1970)),
                ('genres', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
