# Generated by Django 4.1.7 on 2023-03-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_imbd_id_movie_imdb_id_movie_tmdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='imdbId',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image_url',
            new_name='img_path',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tmdb_id',
            new_name='tmdbId',
        ),
    ]
