# Generated by Django 4.1.7 on 2023-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_cast_movie_directors_movie_languages_movie_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='has_seen',
        ),
        migrations.AddField(
            model_name='interaction',
            name='seen_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never heared of it'), ('Heared', 'Just heared about it'), ('Seen', 'I have seen it')], max_length=20, null=True),
        ),
    ]
