# Generated by Django 4.2.2 on 2023-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_directors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.TextField(null=True),
        ),
    ]
