# Generated by Django 4.2.2 on 2023-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_interaction_comparison_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('consent', models.BooleanField()),
            ],
        ),
    ]
