# Generated by Django 4.2.2 on 2023-08-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_participant_given_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.participantinfo'),
            preserve_default=False,
        ),
    ]
