# Generated by Django 4.2.2 on 2023-08-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0023_participant_participant_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantinfo",
            name="id",
        ),
        migrations.AddField(
            model_name="participantinfo",
            name="ParticipantId",
            field=models.IntegerField(null=False, primary_key=True, default=1),
        ),
    ]
