# Generated by Django 4.2.2 on 2023-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_remove_participantinfo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='rank',
            new_name='rank_p1',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='fully_done',
            new_name='fully_p1_done',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='remaining_judge_actions',
            new_name='remaining_p1_judge_actions',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='movies',
        ),
        migrations.AddField(
            model_name='interaction',
            name='rank_p2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='fully_p2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='phaseone_movies',
            field=models.ManyToManyField(related_name='phaseone_participants', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phasetwo_movies',
            field=models.ManyToManyField(related_name='phasetwo_participants', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='participant',
            name='remaining_p2_judge_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='ParticipantId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
