# Generated by Django 4.2.2 on 2023-10-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_participant_gave_p1_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='p1_feedback',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='p2_feedback',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
