# Generated by Django 4.2.2 on 2023-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_participant_p1_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='study_stage',
            field=models.IntegerField(default=1),
        ),
    ]
